development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url:  postgres://rdpgfcqjubefui:21cd37d037f1159545a18e877b7f182133381097c572b17ea637fd1bee10959b@ec2-107-22-187-21.compute-1.amazonaws.com:5432/ddmajdgg9bla92
  channel_prefix: nameofapp_production
